### ISSUE TITLE
Crash on any lwjgl3 Minecraft version (I'm using the new games/lwgjl3 pkg)

### ISSUE THREAD

**Issue by Doctorj128** [pog5/minecraft-freebsd#11]
---- Minecraft Crash Report ----
// Oops.

Time: 2024-04-25 15:49:26
Description: Initializing game

java.lang.ExceptionInInitializerError
        at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1267)
        at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1296)
        at ehn.a(SourceFile:141)
        at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:59)
        at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
        at enn.<init>(SourceFile:483)
        at net.minecraft.client.main.Main.main(SourceFile:211)
        at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
        at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
        at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException: A required function is missing: glfwGetPreeditCursorRectangle
        at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:147)
        at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:141)
        at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:123)
        ... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1267)
        at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1296)
        at ehn.a(SourceFile:141)
        at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:59)
        at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
        at enn.<init>(SourceFile:483)

-- Initialization --
Details:
        Modules: 
Stacktrace:
        at net.minecraft.client.main.Main.main(SourceFile:211)
        at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
        at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
        at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
        Minecraft Version: 1.20
        Minecraft Version ID: 1.20
        Operating System: FreeBSD (amd64) version 14.0-RELEASE
        Java Version: 17.0.10, OpenJDK BSD Porting Team
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), OpenJDK BSD Porting Team
        Memory: 351954096 bytes (335 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes (4096 MiB)
        CPUs: 4
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
        Identifier: Intel64 Family 6 Model 60 Stepping 3
        Microarchitecture: Haswell (Client)
        Frequency (GHz): 2.59
        Number of physical packages: 1
        Number of physical CPUs: 1
        Number of logical CPUs: 1
        Graphics card #0 name: 4th Gen Core Processor Integrated Graphics Controller
        Graphics card #0 vendor: Intel Corporation (Intel Corporation)
        Graphics card #0 VRAM (MB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: rev=0x06
        Virtual memory max (MB): 32606.87
        Virtual memory used (MB): 10200.32
        Swap memory total (MB): 16384.00
        Swap memory used (MB): 0.00
        JVM Flags: 2 total; -Xms512m -Xmx4096m
        Launched Version: 1.20
        Backend library: LWJGL version 3.3.4-snapshot+SNAPSHOT
        Backend API: Unknown
        Window size: <not initialized>
        GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: <disabled>
        Using VBOs: Yes
        Is Modded: Probably not. Client jar signature and brand is untouched
        Type: Client (map_client.txt)
        CPU: <unknown>

**Comment by VVD** [comment]
> glfwGetPreeditCursorRectangle

This feature added in custom patch not merged to upstream of glfw.
Current port graphics/glfw have this patch with default option PREEDIT.
games/lwjgl3 is in ports too.
So this issue is already fixed.
