### ISSUE TITLE
Game fails to start

### ISSUE THREAD

**Issue by TurboWafflz** [pog5/minecraft-freebsd#3]
On my FreeBSD 13.2 system, following these instructions results in Minecraft failing to start, with the following error in the log.

```java
---- Minecraft Crash Report ----
// Oops.
Time: 2023-09-30 12:36:22
Description: Initializing game
java.lang.NoSuchMethodError: 'void org.lwjgl.glfw.GLFWNativeGLX.setPath(org.lwjgl.system.FunctionProvider)'
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
	at eqv.<init>(SourceFile:491)
	at net.minecraft.client.main.Main.main(SourceFile:214)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
	at eqv.<init>(SourceFile:491)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:214)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by pog5** [comment]
Could you post the full log on https://mclo.gs

**Comment by TurboWafflz** [comment]
I actually can't right now, sorry, I'm about to be away from home for a while so I won't have access to this computer and I was going to just quickly get the log now but the hard drive seems to be failing so I can't. This issue should probably just be closed for now I guess, sorry for the inconvenience.

**Comment by pog5** [comment]
Its all fine! Feel free to open another issue or reopen this one any time

**Comment by minneelyyyy** [comment]
I am having this problem, too, on FreeBSD 14. https://mclo.gs/mPBaTOH
